### ISSUE TITLE
Bug in Python 3.6.0 and 3.7.0

### ISSUE THREAD

**Issue by anthonyjclark** [louisabraham/ffpass#17]
I ran into this bug while using `ffpass`:
[configparser.ConfigParser.read() does not accept Pathlib path as a single argument.](https://bugs.python.org/issue29623)

**Fix this error by upgrading your Python version.** I'm leaving this issue here so that others can find it and solve the problem.

Specifically, with Python 3.6.0 (and from the link above it looks like it also affects some versions of 3.7+) I ran into the following error:

```bash
ffpass import -f cpwds.csv
```

```bash
Traceback (most recent call last):
  File "/Users/ajc/miniconda3/bin/ffpass", line 11, in <module>
    sys.exit(main())
  File "/Users/ajc/miniconda3/lib/python3.6/site-packages/ffpass/__init__.py", line 329, in main
    guessed_dir = guessDir()
  File "/Users/ajc/miniconda3/lib/python3.6/site-packages/ffpass/__init__.py", line 223, in guessDir
    config.read(path / "profiles.ini")
  File "/Users/ajc/miniconda3/lib/python3.6/configparser.py", line 693, in read
    for filename in filenames:
TypeError: 'PosixPath' object is not iterable
```

In my case upgrading from 3.6.0 to 3.6.8 fixed the issue.

**Comment by louisabraham** [comment]
Hi, thank for reporting this.

If it is OK with you, I'm going to close this issue and link to it from the readme.

**Comment by anthonyjclark** [comment]
Please do as you see fit.

**Comment by louisabraham** [comment]
Done by aa7f67f
