### ISSUE TITLE
Getting An Error on a CSV exported from 1Password

### ISSUE THREAD

**Issue by Jatckitchens** [louisabraham/ffpass#18]
HI all, I am a bit of newbie, so the answer may be super obvious, but I exported a CSV from 1password to import into firefox.  I reformatted it with just the url, username and password with those three titles as header information.  When I attempt an import, I get the error below... any thoughts?  Thanks!

MacBook-Pro-5:desktop kel$ ffpass import --from passwords.csv
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/ffpass", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ffpass/__init__.py", line 339, in main
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ffpass/__init__.py", line 282, in main_import
    logins = readCSV(args.from_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ffpass/__init__.py", line 181, in readCSV
    for row in reader:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 111, in __next__
    self.fieldnames
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 3846-3847: invalid continuation byte

**Comment by louisabraham** [comment]
Open your CSV file with an hexadecimal editor (I recommend https://ridiculousfish.com/hexfiend/).
Jump to offset 3846 and see if there is anything suspicious (for example a character that appears blank).

**Comment by Jatckitchens** [comment]
Yeah, like I thought, it was a super simple issue :-). I'm embarrassed to say that a bunch of the username fields in my csv file were blank.  As soon as I figured that out and then weeded out all the lines with blank usernames... the import worked like a charm.  This is a seriously good tool... and as far as I can tell, the only way to (ultimately) get your logins from a CSV to an iCloud Keychain.  Anywyas, thanks for making it and providing support for it... well done!

**Comment by louisabraham** [comment]
There is no simple issue :)

I'm not sure why it doesn't work with blank usernames. Were the usernames really blank or did they contain some special byte? Or was a comma missing?
It can actually happen (although it is rare) that a username is blank (for example for an admin interface on a local network).

**Comment by louisabraham** [comment]
I'm closing this but don't hesitate to reopen it if you encounter a problem.
