### ISSUE TITLE
not support utf8?

### ISSUE THREAD

**Issue by chenxuuu** [louisabraham/ffpass#26]
```cmd
C:\Users\chenx\Desktop>ffpass import -f Vivaldi.csv -d C:\Users\chenx\AppData\Roaming\Mozilla\Firefox\Profiles\xxxxxxxx.default-xxxxxxxxx
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\ffpass.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\ffpass\__init__.py", line 346, in main
    args.func(args)
  File "c:\program files\python37\lib\site-packages\ffpass\__init__.py", line 289, in main_import
    logins = readCSV(args.from_file)
  File "c:\program files\python37\lib\site-packages\ffpass\__init__.py", line 187, in readCSV
    for row in reader:
  File "c:\program files\python37\lib\csv.py", line 112, in __next__
    row = next(self.reader)
  File "c:\program files\python37\lib\site-packages\ffpass\__init__.py", line 181, in lower_header
    yield from it
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 2593: illegal multibyte sequence
```

**Comment by chenxuuu** [comment]
import success after I delete all Chinese characters

**Comment by louisabraham** [comment]
Could you just paste here a few Chinese characters that make ffpass bug? This way I'll be able to test!

**Comment by chenxuuu** [comment]
[Vivaldi.zip](https://github.com/louisabraham/ffpass/files/3341467/Vivaldi.zip)
here is

**Comment by Kriattiffer** [comment]
I was able to fix this by passing `encoding = 'utf-8'`  to`argparse.FileType` constructor.

**Comment by chenxuuu** [comment]
@Kriattiffer you can create a pull request

**Comment by louisabraham** [comment]
Hi, I think it should be fixed. I couldn't reproduce on macOS, probably because utf-8 is the default encoding.

Just update to 0.4.8 with `pip install -U ffpass`

**Comment by chenxuuu** [comment]
I tested this
perfect
