### ISSUE TITLE
Invalid syntax at execution

### ISSUE THREAD

**Issue by CriticalKey** [louisabraham/ffpass#30]
Hey there,

i got a syntax error, even though i installed python 3.
Any ideas?
`Marshall:~ kaiser$ ffpass
Traceback (most recent call last):
  File "/usr/local/bin/ffpass", line 9, in <module>
    load_entry_point('ffpass==0.4.7', 'console_scripts', 'ffpass')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/ffpass/__init__.py", line 61
    def getKey(directory: Path, masterPassword=""):
                        ^
SyntaxError: invalid syntax`

**Comment by louisabraham** [comment]
Hi, it really looks like you installed it with python 2.

What command did you use to install `ffpass`? 

Alternatively, you can get a lot of help for installation on https://pythondiscord.com/

**Comment by louisabraham** [comment]
Closing this for the moment.
