### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by crkdsaint** [louisabraham/ffpass#37]
When trying to import 
`sudo ffpass import -f /Users/crkd/Downloads/passwords.csv -d /Users/crkd/Library/Application\ Support/Firefox/Profiles/xxxxxxxx.default-release -v`

It's returning the error
```
There is more than one profile
key=d86f5b93dc06a7e48c74c1b2eb46ceb8a54d5a5e94639236 iv=a53fd0c56705470f
password checked
key=95282f6971b4b7a18f71aa833c5524fd9eeeb83e45f15088 iv=648e12dace0e658d
3deskey a80e02e0a210899d5e2ceff4387fa4efa702baecaddce6c20808080808080808
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 180, in lower_header
    yield next(it).lower()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/ffpass", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 354, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 289, in main_import
    logins = readCSV(args.from_file)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 187, in readCSV
    for row in reader:
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 111, in __next__
    self.fieldnames
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
RuntimeError: generator raised StopIteration
```

Some cursory googling suggests this is due to python 3.7? I'm currently trying on macOS Mojave 10.14. However, I just ran this perfectly fine on macOS Catalina 10.15 the other day with no errors.

**Comment by crkdsaint** [comment]
Not sure the problem, as this was using an export made by ffpass. Tried again with a backup made another way and had success

**Comment by louisabraham** [comment]
I think this might be related to python 3.7, not your macOS version.

If you can reproduce the bug, please download the test version (https://github.com/louisabraham/ffpass/archive/test-3.7.zip), install it with `cd ffpass && pip install .` and tell me if it solves the bug.

**Comment by tomasantunes** [comment]
I get an error: `Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.`

**Comment by louisabraham** [comment]
@tomasantunes do you still get this error?
