### ISSUE TITLE
Issue when ffpass import --from passwords.csv

### ISSUE THREAD

**Issue by vijaypanchal** [louisabraham/ffpass#39]
Traceback (most recent call last):
  File "/usr/local/bin/ffpass", line 11, in <module>
    load_entry_point('ffpass==0.4.8', 'console_scripts', 'ffpass')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/ffpass-0.4.8-py2.7.egg/ffpass/__init__.py", line 61
    def getKey(directory: Path, masterPassword=""):
                        ^
SyntaxError: invalid syntax

**Comment by louisabraham** [comment]
That's because you are using python 2.
