### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by bluetardis** [louisabraham/ffpass#42]
Using OSX 10.14.6 and getting this error.

I have tried installing as both user and sudo.  Any ideas?

```
~/Downloads [ ] $ffpass -h
Traceback (most recent call last):
  File "/usr/local/bin/ffpass", line 9, in <module>
    load_entry_point('ffpass==0.4.8', 'console_scripts', 'ffpass')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/ffpass/__init__.py", line 61
    def getKey(directory: Path, masterPassword=""):
                        ^
SyntaxError: invalid syntax
~/Downloads [ ] $

```

**Comment by louisabraham** [comment]
This is because you are using python 2. Use python 3.
