### ISSUE TITLE
Error trying to import

### ISSUE THREAD

**Issue by sergiobrr** [louisabraham/ffpass#43]
(passw) sergio@alaister:~/virtual/passw$ ffpass import --from ~/secret/Password\ Chrome.csv 
Traceback (most recent call last):
  File "/home/sergio/virtual/passw/bin/ffpass", line 8, in <module>
    sys.exit(main())
  File "/home/sergio/virtual/passw/lib/python3.7/site-packages/ffpass/__init__.py", line 354, in main
    args.func(args)
  File "/home/sergio/virtual/passw/lib/python3.7/site-packages/ffpass/__init__.py", line 287, in main_import
    key = askpass(args.directory)
  File "/home/sergio/virtual/passw/lib/python3.7/site-packages/ffpass/__init__.py", line 254, in askpass
    key = getKey(directory, password)
  File "/home/sergio/virtual/passw/lib/python3.7/site-packages/ffpass/__init__.py", line 69, in getKey
    c.execute("SELECT item1,item2 FROM metadata WHERE id = 'password';")
sqlite3.DatabaseError: file is not a database

**Comment by Silejonu** [comment]
I have a similar error:
`silejonu@silejonu-VirtualBox:~/Téléchargements$ python3.6 ~/.local/bin/ffpass import -f firefox_logins_20191117155446.csv -d /home/silejonu/.mozilla/firefox/1kbonawu.default-release -v
There is more than one profile
key=a845569d4c0ba5157af75dad3780d866220cf8dfed384049 iv=962b956853c32289
password checked
key=34c0bab70780835f68b9753176d6e9a62d20930e58cbd038 iv=c97e2b51c1ca22e1
3deskey a70d37bf2fa2ba58e354e6940bb9cb683dd538570d8015f40808080808080808
Traceback (most recent call last):
  File "/home/silejonu/.local/bin/ffpass", line 11, in <module>
    sys.exit(main())
  File "/home/silejonu/.local/lib/python3.6/site-packages/ffpass/__init__.py", line 354, in main
    args.func(args)
  File "/home/silejonu/.local/lib/python3.6/site-packages/ffpass/__init__.py", line 289, in main_import
    logins = readCSV(args.from_file)
  File "/home/silejonu/.local/lib/python3.6/site-packages/ffpass/__init__.py", line 188, in readCSV
    logins.append((rawURL(row["url"]), row["username"], row["password"]))
KeyError: 'url'
silejonu@silejon`

**Comment by louisabraham** [comment]
Can you reproduce the issue @sergiobrr ?

If yes, please reopen the issue.
