### ISSUE TITLE
Error with exporting on Ubuntu

### ISSUE THREAD

**Issue by bimmerkiev** [louisabraham/ffpass#48]
Hello. When I try to use this app, I receive the error:
`$ ffpass export -v 
Traceback (most recent call last):
  File "/home/user552/.local/bin/ffpass", line 7, in <module>
    from ffpass import main
  File "/home/user552/.local/lib/python3.5/site-packages/ffpass/__init__.py", line 62
    dbfile: Path = directory / "key4.db"
          ^
SyntaxError: invalid syntax
`
Could you help me?
Thanks

**Comment by louisabraham** [comment]
Hi, I think you installed with the wrong version of Python. You need python 3.6 or newer.

**Comment by bimmerkiev** [comment]
You are right. I installed python 3.7 and it works great.
One more question.
I need it for thunderbird, but it crashing with traceback:
`Traceback (most recent call last):
  File "/home/user552/.local/bin/ffpass", line 11, in <module>
    sys.exit(main())
  File "/home/user552/.local/lib/python3.7/site-packages/ffpass/__init__.py", line 354, in main
    args.func(args)
  File "/home/user552/.local/lib/python3.7/site-packages/ffpass/__init__.py", line 269, in main_export
    logins = exportLogins(key, jsonLogins)
  File "/home/user552/.local/lib/python3.7/site-packages/ffpass/__init__.py", line 172, in exportLogins
    decodeLoginData(key, encPassword),
  File "/home/user552/.local/lib/python3.7/site-packages/ffpass/__init__.py", line 129, in decodeLoginData
    assert asn1data[1][0].asTuple() == MAGIC2
AssertionError
`
Is there any way to adopt it to mozilla thunderbird? (there is the same DES3 encryption and the same key4.db file and so on.
I'll be very appreciate, if you can do that.
Thanks in advance.

**Comment by bimmerkiev** [comment]
Please?

**Comment by louisabraham** [comment]
Hi, I don't understand why you need it for Thunderbird. People usually have less than 5 email accounts so they can do it by hand.

Maybe you can just remove the falling assert in the source code and it will work.

If you want a general tool to extract passwords from a user account for multiple apps, there are better tools like LaZagne.

**Comment by louisabraham** [comment]
Closing this, don't hesitate to ask further questions or open another issue if you have other problems.

**Comment by louisabraham** [comment]
Closing this, don't hesitate to ask further questions or open another issue if you have other problems.
