### ISSUE TITLE
No way to import passwords from chrome (FF 84)

### ISSUE THREAD

**Issue by Unixware** [louisabraham/ffpass#57]
all I am getting is this 
(no master pass on FF and database has a "test" entry, so no empty)

`
Traceback (most recent call last):
  File "/home/chris/.local/bin/ffpass", line 8, in <module>
    sys.exit(main())
  File "/home/chris/.local/lib/python3.9/site-packages/ffpass/__init__.py", line 354, in main
    args.func(args)
  File "/home/chris/.local/lib/python3.9/site-packages/ffpass/__init__.py", line 287, in main_import
    key = askpass(args.directory)
  File "/home/chris/.local/lib/python3.9/site-packages/ffpass/__init__.py", line 254, in askpass
    key = getKey(directory, password)
  File "/home/chris/.local/lib/python3.9/site-packages/ffpass/__init__.py", line 74, in getKey
    entrySalt = decodedItem2[0][1][0].asOctets()
AttributeError: 'Sequence' object has no attribute 'asOctets'
`

**Comment by Unixware** [comment]
latest update worked! thx
