### ISSUE TITLE
Firefox import requires at least one saved password in Firefox

### ISSUE THREAD

**Issue by lorenzhs** [louisabraham/ffpass#6]
If you don't have at least one saved password in firefox, the import fails because login.json doesn't exist. This should probably be noted in the README somewhere.

**Comment by spencerdcarlson** [comment]
I ran into the same error:

```bash
ffpass import < ~/Desktop/password.csv 
Traceback (most recent call last):
  File "/usr/local/bin/ffpass", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 292, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 243, in main_import
    key = getKey(args.directory)
  File "/usr/local/lib/python3.7/site-packages/ffpass/__init__.py", line 72, in getKey
    row = next(c)
StopIteration
```

Maybe even a cleaner error message would be helpful

**Comment by louisabraham** [comment]
I think it would be complicated and unsecure to create the file myself. I'll put an exception.

Could you tell me if the "key4.db" file exists @spencerdcarlson? If not, I'll just check if the file exists.

**Comment by nocnokneo** [comment]
I'm still getting an AssertionError instead of a friendly message:

```
python ~/git/ffpass/ffpass/__init__.py import --from /dev/shm/lp.csv 
Traceback (most recent call last):
  File "/home/tbraunjones/git/ffpass/ffpass/__init__.py", line 346, in <module>
    main()
  File "/home/tbraunjones/git/ffpass/ffpass/__init__.py", line 337, in main
    args.func(args)
  File "/home/tbraunjones/git/ffpass/ffpass/__init__.py", line 278, in main_import
    key = askpass(args.directory)
  File "/home/tbraunjones/git/ffpass/ffpass/__init__.py", line 245, in askpass
    key = getKey(directory, password)
  File "/home/tbraunjones/git/ffpass/ffpass/__init__.py", line 89, in getKey
    assert row[1] == MAGIC1  # CKA_ID
AssertionError
```

**Comment by louisabraham** [comment]
@nocnokneo I don't know why you get this error, but it's not because your password database doesn't exist.

The code around your error looks like that https://github.com/louisabraham/ffpass/blob/master/ffpass/__init__.py#L84-L89

The problem is that no row verified the property `assert row[1] == MAGIC1`, which shouldn't be the case. If your password database is really empty, you should delete `key4.db` and `logins.json`.

**Comment by nocnokneo** [comment]
Hm, I'm not sure what the explanation is, but as soon as I added a password
to Firefox, this error when away.

>

**Comment by louisabraham** [comment]
I think your database might just have been buggy...
Firefox might have recreated it. I can add a friendly message that asks to add a password.
