### ISSUE TITLE
AssertionError: The key is encoded with an unknown format (1, 2, 840, 113549, 1, 5, 13)

### ISSUE THREAD

**Issue by phijor** [louisabraham/ffpass#61]
I'm trying to import my passwords from `chromium`, but get hit by the following error:

```
$ ffpass import --file '/tmp/Chrome Passwords.csv' -d ~/.mozilla/firefox/<profile>.default
Traceback (most recent call last):
  File "/path/to/virtualenvs/ffpass-_a4N4bz3/bin/ffpass", line 8, in <module>
    sys.exit(main())
  File "/path/to/virtualenvs/ffpass-_a4N4bz3/lib/python3.9/site-packages/ffpass/__init__.py", line 419, in main
    args.func(args)
  File "/path/to/virtualenvs/ffpass-_a4N4bz3/lib/python3.9/site-packages/ffpass/__init__.py", line 338, in main_import
    key = askpass(args.directory)
  File "/path/to/virtualenvs/ffpass-_a4N4bz3/lib/python3.9/site-packages/ffpass/__init__.py", line 307, in askpass
    key = getKey(directory, password)
  File "/path/to/virtualenvs/ffpass-_a4N4bz3/lib/python3.9/site-packages/ffpass/__init__.py", line 122, in getKey
    assert oid == MAGIC3, f"The key is encoded with an unknown format {oid}"
AssertionError: The key is encoded with an unknown format (1, 2, 840, 113549, 1, 5, 13)
```

### Firefox

```
$ firefox --version
Mozilla Firefox 86.0
```

### ffpass

`ffpass 0.5.0`

**Comment by louisabraham** [comment]
This is weird, are you able to export passwords from ff? If you don't have any, just manually add an entry.

**Comment by bgkerion** [comment]
I have the same problem and I'm able to export password from FF
