### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by Stach00** [louisabraham/ffpass#7]
ffpass export  --to passwords.csv -d C:\Users\username\Desktop\

Traceback (most recent call last):
  File "c:\users\stachu\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\stachu\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Stachu\AppData\Local\Programs\Python\Python37-32\Scripts\ffpass.exe\__main__.py", line 9, in <module>
  File "c:\users\stachu\appdata\local\programs\python\python37-32\lib\site-packages\ffpass\__init__.py", line 292, in main
    args.func(args)
  File "c:\users\stachu\appdata\local\programs\python\python37-32\lib\site-packages\ffpass\__init__.py", line 232, in main_export
    key = askpass(args.directory)
  File "c:\users\stachu\appdata\local\programs\python\python37-32\lib\site-packages\ffpass\__init__.py", line 223, in askpass
    key = getKey(directory, password)
  File "c:\users\stachu\appdata\local\programs\python\python37-32\lib\site-packages\ffpass\__init__.py", line 57, in getKey
    c.execute("SELECT item1,item2 FROM metadata WHERE id = 'password';")
sqlite3.OperationalError: no such table: metadata

**Comment by louisabraham** [comment]
Hi Stan,

I see you are using Windows. Note that I did not configure yet the automatic profile detection on this OS so you have to use -d to provide the location of your Firefox profile, and after that it should be fine. I think you can find this information by following the instructions on https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data

If you succeed, please let me know so that I can remove the need for -d!

**Comment by Stach00** [comment]
it worked - but I had to figure out it by myself - please update the manual
- widnows users are also users.
Thanks for fast (almost immidiate) reply.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by louisabraham** [comment]
Could you please send me the command you used?

**Comment by Stach00** [comment]
Well I used this one at the beginning:

ffpass export > passwords.csv

 

but it required directory which in “sample is not shown” and manual  shows it like that

 

  -d DIRECTORY, --directory DIRECTORY, --dir DIRECTORY
                        Firefox profile directory

 

I was unable to catch by my eye that it is Firefox directory

I received some stack trace so I figured that thanks to stack  trace.

Just modify the sample usage with -d like

 

ffpass -d [Firefox Profile Directory] export > passwords.csv
 
Sample on Windows 
ffpass -d C:\Users\MYUSERNAME\AppData\Local\Mozilla\Firefox\Profiles\l6gaczpp.default-1542711909749 export > passwords.csv
 

on linux it will be similar situation I guess

 

Cheers

**Comment by louisabraham** [comment]
Thank you! The automatic folder detection is already activated for Linux and macOS.

**Comment by louisabraham** [comment]
Hi again, could you upgrade to the latest version of ffpass and try again without the -d argument?
